### ISSUE TITLE
对于SliverList，数据源变更后，如何jumpTo的很平滑，没有闪烁的视觉

### ISSUE THREAD

**Issue by runfengai** [fluttercandies/flutter_scrollview_observer#105]
### Content

如题，当前展示了itemA这一条数据，当我展开后，数据源变为10条，itemA在中间第五条。此时我直接observerController.jumpTo(4)，会自动跳到一个比较诡异的地方【可能是2/3】,于是尝试用WidgetsBinding.instance.addPostFrameCallback((_){})倒是可以滑动到目标位置，但是有明显的闪烁感，体验有点差。

tks!

**Comment by LinXunFeng** [comment]
你展开的 `item` 都很大吗？如果很大，那 `scrollview_observer` 无法观察到未渲染的 `item`，所以会采用翻页的方式去使其加载出来，这可能是你说的闪烁问题。

如果你的 `item` 是固定高的，那可以使用 `isFixedHeight` 解决，如： `observerController.jumpTo(index: 4, isFixedHeight: true);`。

如果不是等高，那无解，只能适当调整 `cacheExtent` 去缓解这种现象

**Comment by runfengai** [comment]
我之前在android上的思路是，先滚动，当items都渲染完成后，补上后边的滚动操作，但是看flutter好像对这方面的支持不够友好。感谢。
