### ISSUE TITLE
在嵌套的 ListView 中无法检测可见 item 

### ISSUE THREAD

**Issue by xiejianchao** [fluttercandies/flutter_scrollview_observer#27]
1级 ListView 可以检测，嵌套的 2级 ListView 无法检测。

**Comment by LinXunFeng** [comment]
尝试使用 `sliverListContexts` 去指定你的二级 `ListView`
相关使用说明：[flutter_scrollview_observer#method-2-specify-buildcontext-for-sliver](https://github.com/LinXunFeng/flutter_scrollview_observer#method-2-specify-buildcontext-for-sliver)

**Comment by xiejianchao** [comment]
不好意思，刚看到，好像还不行，测试代码如下，是用的不对吗？
`@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ListViewObserver(
          sliverListContexts: () {
            return [if (_sliverListViewContext != null) _sliverListViewContext!];
          },
          child: _buildListView(),
          onObserve: (resultMap) {
            if (resultMap.firstChild != null) {
              int index = resultMap.firstChild!.index;
              print("1 级 ListView 可见的 item:$index");
              print('1 级 ListView 剩余可见 item:${resultMap.displayingChildIndexList}');
            }
          },
        ),
      ),
    );
  }

  ListView _buildListView() {
    return ListView.builder(
      scrollDirection: Axis.vertical,
      itemCount: 1,
      itemBuilder: (context, index) {
        if (_sliverListViewContext != context) {
          _sliverListViewContext = context;
        }
        return Column(
          children: [
            Container(
              height: 100,
              alignment: Alignment.center,
              width: MediaQuery.of(context).size.width,
              color: Colors.green,
              child: Text("item level1 $index"),
            ),
            Container(
              width: MediaQuery.of(context).size.width,
              color: Colors.grey,
              child: _buildListViewObserver2(),
            )
          ],
        );
      },
    );
  }

  _buildListViewObserver2() {
    return ListViewObserver(
      sliverListContexts: () {
        return [if (_sliverListViewContext2 != null) _sliverListViewContext2!];
      },
      child: ListView.builder(
        shrinkWrap: true,
        physics: const NeverScrollableScrollPhysics(),
        itemCount: list2.length,
        itemBuilder: (context, index) {
          if (_sliverListViewContext2 != context) {
            _sliverListViewContext2 = context;
          }
          return Container(
            color: Colors.pink,
            margin: const EdgeInsets.only(left: 100),
            height: 60,
            child: Text("item level2 index:$index"),
          );
        },
      ),
      onObserve: (resultMap) {
        if (resultMap.firstChild != null) {
          int index = resultMap.firstChild!.index;
          print("2 级 ListView 可见的 item:$index");
          print('2 级 ListView 剩余可见 item:${resultMap.displayingChildIndexList}');
        }
      },
    );
  }`

**Comment by LinXunFeng** [comment]
你的 `ListView 2` 设置成了不滚动，所以该库内部使用的 `NotificationListener<ScrollNotification>` 监听不到

解决方案：
```dart
NotificationListener<ScrollNotification>(
  onNotification: (notification) {
    observerController2.dispatchOnceObserve();
    return false;
  },
  child: _buildListView(),
);
```

虽然你可以用上述代码监听 `ListView 1` 在滚动时触发该库对 `ListView 2` 的观察，但是由于你的  `ListView 2` 是被 `Column` 包裹的，所以再怎么观察你的  `ListView 2` 都是全量展示的


所以这里还是建议你使用 `CustomScrollView` 的 `slivers` 去实现你这个功能，避免上述问题

**Comment by xiejianchao** [comment]
感谢回复，问题已解决，非常感谢。
