### ISSUE TITLE
1.14.0版本：异常报告

### ISSUE THREAD

**Issue by wangyang3-ola** [fluttercandies/flutter_scrollview_observer#35]
大佬，帮忙看下这个异常 是否有修复
Non-fatal Exception: Null check operator used on a null value
0  ???                            0x0 State-context + 954 (framework.dart:954)
1  ???                            0x0 ObserverWidgetState-fetchTargetSliverContexts + 201 (observer_widget.dart:201)
2  ???                            0x0 ObserverWidgetState-_setupSliverController.<fn> + 175 (observer_widget.dart:175)
3  ???                            0x0 SchedulerBinding-_invokeFrameCallback + 1289 (binding.dart:1289)
4  ???                            0x0 SchedulerBinding-handleDrawFrame + 1227 (binding.dart:1227)
5  ???                            0x0 SchedulerBinding-_handleDrawFrame + 1076 (binding.dart:1076)

**Comment by LinXunFeng** [comment]
麻烦请提供一下可复现问题的 `Demo`

**Comment by wangyang3-ola** [comment]
app线上有个用户上报的这个异常，本地暂时没法复现

**Comment by LinXunFeng** [comment]
你们使用的 `Flutter` 版本是多少？

**Comment by wangyang3-ola** [comment]
Flutter 3.7.12

**Comment by wangyang3-ola** [comment]
好的 谢谢
