### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [fluttercandies/flutter_scrollview_observer#55]
### Platforms

dart

### Description

I'm using SuperSliverList from [super_sliver_list](https://pub.dev/packages/super_sliver_list) package. can you add support for this? cause you are checking the type of sliver in the package codebase:

` if (_obj is RenderSliverList || _obj is RenderSliverFixedExtentList) {}`

### Why

super_sliver_list solves performance issues, especially when you wanna use the Scrollbar

**Comment by LinXunFeng** [comment]
For ScrollView built by third-party package, you need to tell the `scrollview_observer` how to observe it.

```dart
extendedHandleObserve: (context) {
  // The _sliverListCtx is BuildContext of SuperSliverList.
  if (context == _sliverListCtx) {
    return ObserverCore.handleListObserve(context: context);
  }
  return null;
},
```

**Comment by Shahmirzali-Huseynov** [comment]
thanks, I think it's working.
