### ISSUE TITLE
padding in CustomScrollView

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [fluttercandies/flutter_scrollview_observer#57]
### Platforms

dart

### Description

What is the right way to use padding for SliverList in CustomScrollview for this package? cause you mention this in the doc.

<img width="418" alt="Screenshot 2023-10-29 at 10 32 09" src="https://github.com/fluttercandies/flutter_scrollview_observer/assets/49102327/7ad44be0-5f72-46d3-9025-6333eaba82c9">

**Comment by LinXunFeng** [comment]
Oh, that was a problem in a very old version, you can use `SliverPadding` in `CustomScrollView`, I updated the documentation, thanks for the reminder.

**Comment by Shahmirzali-Huseynov** [comment]
thanks, I used SliverPadding.
