### ISSUE TITLE
ListView reverse: true,  当前显示 displayingChildIndexList  是乱的，如何解决？？

### ISSUE THREAD

**Issue by ymkil** [fluttercandies/flutter_scrollview_observer#63]
### Version

1.18.1

### Platforms

dart

### Device Model

all

### flutter info

```sh
all
```

### How to reproduce?

reverse: true

**Comment by LinXunFeng** [comment]
我自己试了不会，你可以提供一个最小可复现的 `Demo` 吗？

**Comment by ymkil** [comment]
在 very_good_infinite_list 是乱的，这个插件的问题 。ListView 是正常的，不好意思
