### ISSUE TITLE
How to set duration for initial index

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [fluttercandies/flutter_scrollview_observer#65]
### Platforms

dart

### Description

I don't want animation. It takes time to scroll to the index. I want to jump directly to the relevant index when I navigate to a page.

### My code

```
 final sliverScrollController = useScrollController();
    final observerController = useMemoized(
      () => SliverObserverController(controller: sliverScrollController)
        ..initialIndexModelBlock = () => ObserverIndexPositionModel(
              index: lastReadedAyahIndex ?? 0,
              sliverContext: sliverListCtx.value,
              offset: (targetOffset) {
                final customScrollViewRenderObj = (customScrollViewKey.currentContext?.findRenderObject() as RenderBox);
                return customScrollViewRenderObj.size.height * 0.5;
              },
              alignment: 0.1,
            ),
    );

```
https://github.com/fluttercandies/flutter_scrollview_observer/assets/49102327/f6aba89f-4aeb-43b5-861a-8fc2b5a4f001

**Comment by LinXunFeng** [comment]
Please look at the first paragraph in the [document](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/2%E3%80%81Scrolling-to-the-specified-index-location).

This package can only calculate the accurate offset after the target item is rendered.

**Comment by Shahmirzali-Huseynov** [comment]
it means it's not possible without duration ?

**Comment by LinXunFeng** [comment]
> - If child widgets are fixed height in scrollView, use `isFixedHeight` instead of `cacheExtent`.
> - For scrollView such as detail page, it is recommended to set `cacheExtent` to `double.maxFinite`.

Currently there are only the above two ways to avoid page turning.

**Comment by Shahmirzali-Huseynov** [comment]
I did cacheExtent to double.maxFinite. but now there is lag. you can see in the video.


https://github.com/fluttercandies/flutter_scrollview_observer/assets/49102327/298b4f07-a027-47ac-b8c3-873bdf0da420

**Comment by LinXunFeng** [comment]
Yes, setting `cacheExtent` to `double.maxFinite` means that all items of `ScrollView` will be rendered. It is time-consuming. You need to make a choice based on your own scenario.

For example, if the content of the`ScrollView` is not too much, you can show 'Loading' on the page during at the beginning, and `ScrollView` is displayed after the page push is completed. For performance reasons, you can reset cacheExtent after scrolling to the index.

**Comment by Shahmirzali-Huseynov** [comment]
thanks your suggestions
