### ISSUE TITLE
[How to use] 首次进入页面，onObserveAll没有回调

### ISSUE THREAD

**Issue by wangxp423** [fluttercandies/flutter_scrollview_observer#68]
### Platforms

dart

### Description

首次进入页面，onObserveAll没有回调，滑动抬起手指以后才有，这个是那个配置？没找到到呀

**Comment by LinXunFeng** [comment]
目前没有提供相关配置，需要你自己手动触发一次观察

```dart
override
void initState() {
  super.initState();

  // Trigger an observation manually
  Future.delayed(const Duration(milliseconds: 500)).then((value) {
    ListViewOnceObserveNotification().dispatch(_sliverListViewContext);
  });
}
```

**Comment by LinXunFeng** [comment]
该库的主要观察对象是列表和网格里的item，对于sliver的观察是 `onObserveViewport` 回调，目前能给的信息内容较弱，想问下你是什么使用场景？

**Comment by LinXunFeng** [comment]
可以在 `onObserveViewport` 中拿到观察结果数据模型，然后去遍历 `.displayingChildModelList` 判断 `sliverContext` 是否与你的 `sliverToBoxAdapter` 对应的 `BuildContext` 是否相等，如果是则显示，否则为没有显示。
