### ISSUE TITLE
如何获取使用sticky_header时的索引

### ISSUE THREAD

**Issue by yyong37** [fluttercandies/flutter_scrollview_observer#71]
### Platforms

dart

### Description

[example：multi_sliver_demo_page](https://github.com/fluttercandies/flutter_scrollview_observer/blob/fc2894191a4d94cda1986f0aeefb5c6087aed3f2/example/lib/features/custom_scrollview/custom_scrollview_demo/multi_sliver_demo_page.dart )

请问在该示例中，我该如何获取section的索引？

**Comment by LinXunFeng** [comment]
`sliver` 的下标无法直接拿到，需要你自己记录与维护一个 `Map<BuildContext, int>`，存储的内容为：`{sliverCtx : index}`，再结合  `onObserveViewport` 回调可以获取当前的第一个 `sliverCtx`，通过这种方式可以间接拿到索引。

**Comment by yyong37** [comment]
谢谢你的解答。我现在按照你说的在onObserveViewPort中没有任何输出，是我忽略了什么东西吗？
```
SliverViewObserver(
        controller: sliverObserverController,
        sliverContexts: () => contextList,
// this line
        onObserveViewport: (result) {
          final firstChildCtxInViewport = result.firstChild.sliverContext;
          debugPrint('first child ctx-- $firstChildCtxInViewport');
        },
        child: CustomScrollView(......)
```

**Comment by LinXunFeng** [comment]
很有可能是你传入的 `sliverContexts` 用的不是最外层的 `sliver`
相关说明：[1.3、onObserveViewport 回调](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/1%E3%80%81%E7%9B%91%E5%90%AC%E6%BB%9A%E5%8A%A8%E8%A7%86%E5%9B%BE%E4%B8%AD%E6%AD%A3%E5%9C%A8%E6%98%BE%E7%A4%BA%E7%9A%84%E5%AD%90%E9%83%A8%E4%BB%B6#13onobserveviewport-%E5%9B%9E%E8%B0%83)

建议你用两个 `SliverViewObserver`，一个负责观察 `item`，另一个负责观察 `sliver`，这样也能区分开 `sliverContexts`
