### ISSUE TITLE
[Discussions] Is it possible with this package to use InfiniteListViewPage with dynamic offset?

### ISSUE THREAD

**Issue by vergaraSC** [fluttercandies/flutter_scrollview_observer#76]
### Content

I was using the example that you handle Is it InfiniteListViewPage, but the content that is handled in that example has a specific height, in my case I want the content to be dynamic, and to know which is the item that is visible on the screen, is it possible to get it with your package?

**Comment by LinXunFeng** [comment]
Yes, the sample code has been updated and can be previewed online via the [https://fluttercandies.github.io/flutter_scrollview_observer](https://fluttercandies.github.io/flutter_scrollview_observer), and the console will output the item that is currently being displayed.
