### ISSUE TITLE
[How to use] Bug in example

### ISSUE THREAD

**Issue by geghamh2** [fluttercandies/flutter_scrollview_observer#77]
### Platforms

ANDROID

### Description

In your example in ChatPage, when we change    _addMessage(RandomTool.genInt(min: 1, max: 3))=> _addMessage(RandomTool.genInt(min: 10, max: 15)); keep position is not  working correctly;

**Comment by LinXunFeng** [comment]
Please refer to the last description of [3.1、Basic usage](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/3%E3%80%81Chat-Observer#31basic-usage)

> Note: This feature relies on the latest message view before the message is inserted as a reference to calculate the offset, so if too many messages are inserted at once and the reference message view cannot be rendered, this feature will fail, and you need to try to avoid this problem by setting a reasonable value for `cacheExtent` of `ScrollView` by yourself!
>
> The size calculation of cacheExtent can refer to the following formula: 
>
>```
>cacheExtent = [maximum height of a message] * [number of messages inserted at one time] + 200
>```
