### ISSUE TITLE
[Feature request] Support visibleFraction in ObserverModel

### ISSUE THREAD

**Issue by cogivn** [fluttercandies/flutter_scrollview_observer#80]
### Platforms

Android, iOS

### Description

Hi,

Thank you for creating a wonderful library.
 It is very helpful for me and can we add field as visibleFraction in ObserverModel? 
A fraction in the range [0,...,1] that represents what proportion of the widget is visible (assuming rectangular bounding boxes).

### Why

When the `displayingChildModelList` field represents [0, 1, 2] and the `visibleFraction` is aligned on each record [0.5, 0.2, 0.3]. so we can choose the best index which in this case is 0 instead of taking the first or last index in displayChildModelList.

**Comment by LinXunFeng** [comment]
Good idea, `visibleFraction` has been added to the development branch, you can try it to see if it satisfies your requirement.

**Comment by cogivn** [comment]
Hi @LinXunFeng,

The visibleFraction field seems to be working well too.  
I'll close this ticket now. Thanks so much!

**Comment by LinXunFeng** [comment]
Version `1.20.0` has been released and includes this property.
