### ISSUE TITLE
[Feature request] Can SliverObserverController be used with ChatScrollObserver?

### ISSUE THREAD

**Issue by thaidmfinnick** [fluttercandies/flutter_scrollview_observer#81]
### Platforms

macOS

### Description

Hi, thank for very useful library in Flutter World!

I want to use feature of listView is: **fixed to the current chat position** for CustomScrollView? Is it possible?

Thank you and look forward to seeing your response!

### Why

My final desire feature is to keep scroll when elements of custom scroll view change index, resize. I find this library and it's very clear to me, and I go half of road to complete this feature. I found this wiki [here](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/3%E3%80%81Chat-Observer) to handle keep scroll with `ListObserverController`.

**Comment by thaidmfinnick** [comment]
Oh I find a way to use `ListViewObserver`, the my only problem is can I keep current position of one of my child update height? (Like children of 1 thread have new messages and scroll cannot keep position). Thanks! 

https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/be24825c-a750-41e6-9424-a3b001844f78

**Comment by LinXunFeng** [comment]
You can complete it by setting the model to `ChatScrollObserverHandleMode.specified` and specifying the indexes of the reference items before and after inserting the message.

Assume that you are currently changing the content of the item with index 0, then the index of the reference item before and after the change can be specified as 1.

```dart
chatObserver.standby(
  mode: ChatScrollObserverHandleMode.specified,
  refItemRelativeIndex: 1,
  refItemRelativeIndexAfterUpdate: 1,
);

final model = chatModels[0];
final newModel = ChatModel(
  isOwn: model.isOwn,
  content: model.content + '123abc',
);
chatModels[0] = newModel;
setState(() {});
```

See [3.4、Specifies the referenced item](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/3%E3%80%81Chat-Observer#34specifies-the-referenced-item) for more information.

**Comment by thaidmfinnick** [comment]
Thanks for quick response, I have tried but it's not working, to not misunderstand I record a video below:

I have many threads, when 1 thread is update with new message, the scroll position is jump follow, the update messages are children of thread so I guess the index of the reference item is still 0 and not change.

 I have successfully insert new thread(not messages children of thread) without scroll position but this case isn't.

https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/ef6be18d-ee7c-409d-87c1-93337701c6b4

**Comment by LinXunFeng** [comment]
Oh, you misunderstood. The reference item should not be the item whose content has changed, but item that do not change.

For example, in thread0, the content of its children has changed, then the reference should be thread1/thread2 etc.

```dart
chatObserver.standby(
  mode: ChatScrollObserverHandleMode.specified,
  refItemRelativeIndex: 1, // or 2...
  refItemRelativeIndexAfterUpdate: 1,  // or 2...
);
```

If you insert a new thread, the original thread0 will become thread1, and the new thread will become thread0. In this scenario, what changes is the new thread, and what remains unchanged is all the original threads. In this case, the reference thread can be the original thread0.

```dart
chatObserver.standby(
  mode: ChatScrollObserverHandleMode.specified,
  refItemRelativeIndex: 0, // The index of original thread0 before inserting a new thread.
  refItemRelativeIndexAfterUpdate: 1, // The index of original thread0 after inserting a new thread.
);
```

It is worth noting that the reference thread/children needs to be rendered before and after the change.

**Comment by thaidmfinnick** [comment]
I try and succeedddd, thank you very muchhh!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Before closing issue, I have one more question, what actually refItem relative index use for?

**Comment by thaidmfinnick** [comment]
Very informative, so what if I choose refItemRelativeIndex outside of screen? I test but cannot see the differences. Also, when I test, the child with (current index =  refItemRelativeIndex) will keep scroll when I update other child above? is it correct?

P/s: I really appreciate your support, I have sent you a small gift, do you receive it??

**Comment by LinXunFeng** [comment]
> so what if I choose refItemRelativeIndex outside of screen?

You can use the `refItemRelativeIndex` outside of screen, as long as it is rendered before and after the change, but I still recommend that you use the index of the unchanged child closest to the changed child as much as possible.

> when I test, the child with (current index = refItemRelativeIndex) will keep scroll when I update other child above? is it correct with logic?

I think this may be caused by the current offset of the ListView not exceeding `fixedPositionOffset`, which you need to check.

See [3.1、Basic usage](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/3%E3%80%81Chat-Observer#31basic-usage) for more information.


> I have sent you a small gift as my thankss, have you received it??

I received your gift, thank you very much. 😁

**Comment by thaidmfinnick** [comment]
close as resolved!

**Comment by thaidmfinnick** [comment]
Everything is work as expected, only 1 case I show in video:

my piece code for test: 
```
chatObserver.fixedPositionOffset = -1

chatObserver.standby(
      mode: ChatScrollObserverHandleMode.specified,
      refItemRelativeIndex: 2,
      refItemRelativeIndexAfterUpdate: 2
);
```
I choose `refItemRelativeIndex = 2`, it means, scroll will not change at index 2 from viewport, right? So as my understand, when child at index 0, and 1 in viewport update, it will scroll upward instead of scroll downward in video demo. Do you know the reason? Correct me if I'm wrong. Thankss!

https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/7955b760-a8cc-48a0-8db0-59b577317294

**Comment by LinXunFeng** [comment]
<img width="1304" alt="image" src="https://github.com/fluttercandies/flutter_scrollview_observer/assets/19367531/3b437243-066e-4124-91db-d3484ff04b2c">

Based on your video, I guess the `reserve` of your ListView should be true, so the relative indexes are also in reverse order.

When the content of child2 changes, the `refItemRelativeIndex` you specify is also 2. After comparing before and after, the offset of child2 has not changed.

When the content of child1 changes, child2 is affected by child1, the child2's offset increases. However, due to the keep position functionality acts on child2, so what you see is that child1 increases downward.

**Comment by thaidmfinnick** [comment]
No, the ListView I setup is not reverse, it's normal listview.

**Comment by LinXunFeng** [comment]
```dart
chatObserver.fixedPositionOffset = -1;

...

final result = await observerController.dispatchOnceObserve(
  isForce: true,
  isDependObserveCallback: false,
);
final displayingFirstChildIndex = result.observeResult?.firstChild?.index ?? 0;
final model = observerController.observeFirstItem();
final cacheFirstChildIndex = model?.index ?? 0;
final detal = displayingFirstChildIndex - cacheFirstChildIndex;

refItemRelativeIndex = 2 + deal;
chatObserver.standby(
  mode: ChatScrollObserverHandleMode.specified,
  refItemRelativeIndex: refItemRelativeIndex,
  refItemRelativeIndexAfterUpdate: refItemRelativeIndex,
);
```

Adjust the code and try it.

**Comment by thaidmfinnick** [comment]
Yeah, it's work, only some situations, although I always listen and lock position to last display relative index, it's still scroll downward like in video, but after I scroll up a little bit, it's correct again. I'm not sure but it means to you in this situation?

https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/7c0501d2-c10b-496c-b3f0-8bbe02fb1e67

**Comment by LinXunFeng** [comment]
Is your `refItemRelativeIndex` always 1?

**Comment by thaidmfinnick** [comment]
No, I change depends on last display relative index, if my view has [0, 1, 2], I will lock 2, if [0, 1], I will lock 1.

**Comment by thaidmfinnick** [comment]
I don't know it's a bug, or not. but i will show in video below:

I have 3 threads in view => I lock position on last relative index: 2
I type on thread with index 1
If first thread have 100% visibility: => I type in thread 1 and thread 1 will jump as I expected
But I scroll down to hide first thread only a little => I type and it's scroll down

My teammates and I are discussing about weird situation. It's about calculation offset, right?

https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/33e87208-e7fd-4d1d-9256-ce0f9e569326

**Comment by LinXunFeng** [comment]
This seem strange. You need to confirm the index of the first child currently being displayed through the following code.

```dart
final result = await observerController.dispatchOnceObserve(
  isForce: true,
  isDependObserveCallback: false,
);
final displayingFirstChildIndex = result.observeResult?.firstChild?.index ?? 0;
debugPrint('displayingFirstChildIndex -- $displayingFirstChildIndex');
```

Have you set `leadingOffset` or `dynamicLeadingOffset`?

**Comment by thaidmfinnick** [comment]
> Have you set leadingOffset or dynamicLeadingOffset?

No i'm not.

Oh, do I miss something? `displayingFirstChildIndex` change?
https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/4a61033d-a67d-43c4-bff9-e076badee76b

**Comment by LinXunFeng** [comment]
This may be an illusion. Have you set paddingBottom for thread to implement separator?

To confirm this, you can set a background color for the thread and print its `displayPercentage`.

```dart
final result = await observerController.dispatchOnceObserve(
  isForce: true,
  isDependObserveCallback: false,
);
final firstChild = result.observeResult?.firstChild;
final index = firstChild?.index ?? 0;
final displayPercentage = firstChild?.displayPercentage ?? 0;
debugPrint('firstChild -- $index - $displayPercentage');
```

**Comment by thaidmfinnick** [comment]
> This may be an illusion. Have you set paddingBottom for thread to implement separator?

I have marginBottom: 24.

**Comment by thaidmfinnick** [comment]
It stills weird, although `indexLock = 2`, it's still scroll down. As your code you guide me, I print and only 3 items in list. You can see details in video:

https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/afab85ae-e117-4e1f-bd9b-494c0db1cfa2

**Comment by thaidmfinnick** [comment]
Do you calculate anything related to first child with 50% percentage? I test when first child has displayPercentage > 50%, thread 1 will scroll down, else if will scroll up.

**Comment by LinXunFeng** [comment]
I’m not sure where the problem lies just by watching the video. You can debug the following code breakpoints in `chat_observer_scroll_physics_mixin.dart`.

Note that the keep position functionality will only take effect when you go to the third point.

https://github.com/fluttercandies/flutter_scrollview_observer/blob/e2faec792269bb6cbea51b4e7a1c983fb002607f/lib/src/utils/src/chat/chat_observer_scroll_physics_mixin.dart#L38

https://github.com/fluttercandies/flutter_scrollview_observer/blob/e2faec792269bb6cbea51b4e7a1c983fb002607f/lib/src/utils/src/chat/chat_observer_scroll_physics_mixin.dart#L47

https://github.com/fluttercandies/flutter_scrollview_observer/blob/e2faec792269bb6cbea51b4e7a1c983fb002607f/lib/src/utils/src/chat/chat_observer_scroll_physics_mixin.dart#L56

Or can you provide a reproducible demo?

**Comment by thaidmfinnick** [comment]
Oke, let me try to reproduce based on example. I will response as soon as possible! Thanks

**Comment by thaidmfinnick** [comment]
I can reproduce my issue in create a demo file in example in your repo, I have forked and you can test. I put my reproducable case in `my_test.dart`. Do I need create another issue? 

https://github.com/thaidmfinnick/flutter_scrollview_observer

![Screenshot 2024-05-16 at 14 31 26](https://github.com/fluttercandies/flutter_scrollview_observer/assets/83997264/dc1255ae-66b8-4ffd-b47d-7b9b3cbefbed)

**Comment by LinXunFeng** [comment]
> Do I need create another issue?

No, I think it's the same issue.

Please adjust the code as follows and try again.

```diff
int lastRelativeIndex = 1;
+ int currentFirstChildIndex = 0;
```

```diff
onObserve: (result) {
+  currentFirstChildIndex = result.firstChild?.index ?? 0;
  lastRelativeIndex = result.displayingChildIndexList.length - 1;
},
```

```diff
floatingActionButton: FloatingActionButton(
    onPressed: () {
      print('lastRelativeIndex:$lastRelativeIndex');
      chatScrollObserver.fixedPositionOffset = -1;
+       final model = observerController.observeFirstItem();
+       final cacheFirstChildIndex = model?.index ?? 0;
+       final delta = currentFirstChildIndex - cacheFirstChildIndex;
+       final refItemRelativeIndex = lastRelativeIndex + delta;
      chatScrollObserver.standby(
        mode: ChatScrollObserverHandleMode.specified,
-          refItemRelativeIndex: lastRelativeIndex,
-          refItemRelativeIndexAfterUpdate: lastRelativeIndex,
+         refItemRelativeIndex: refItemRelativeIndex,
+         refItemRelativeIndexAfterUpdate: refItemRelativeIndex,
      );
      setState(() {
        heightForMid += 50;
      });
    },
    child: Icon(Icons.add)),
```

**Comment by thaidmfinnick** [comment]
Oh my god, it's work perfect, you are magician. Why cache is different in this case?

**Comment by LinXunFeng** [comment]
First of all, I'm sorry. There was a slight mistake in yesterday's picture. I misled you. 😅

<img width="1468" alt="image" src="https://github.com/fluttercandies/flutter_scrollview_observer/assets/19367531/e1cccf40-5f44-4077-8b6a-de16e48a5a87">

As shown in the figure above, `observeFirstItem` will get the first rendered item, even if it is off-screen. Currently, the internal logic of keeping the position functionality also uses `observeFirstItem`.

Therefore, in order to achieve the relative index logic mentioned yesterday, I used delta to correct.

In the next version, I will add a new parameter to provide this correction logic, so that everyone does not have to correct it by themselves.

**Comment by thaidmfinnick** [comment]
ok, I understand your idea, and again thank you very much for your unfailing support. I will follow your repos, and use it. 
See you again in other issues!

**Comment by LinXunFeng** [comment]
Version 1.20.0 has been released.

You can adjust the code without `delta` as follows.

```dart
final refItemIndex = currentThreadIndex + 1;

chatObserver.standby(
  mode: ChatScrollObserverHandleMode.specified,
  refIndexType: ChatScrollObserverRefIndexType.itemIndex,
  refItemIndex: refItemIndex,
  refItemIndexAfterUpdate: refItemIndex,
);```

**Comment by thaidmfinnick** [comment]
Thanks! I have tested your above code you provide and it works perfect. You divide into 3 specific cases: `relativeIndexStartFromCacheExtent`, `relativeIndexStartFromDisplaying` and `itemIndex`. So clear to me!
