### ISSUE TITLE
怎样用到NestedScrollView嵌套两个并行的listview?

### ISSUE THREAD

**Issue by cjl84914** [fluttercandies/flutter_scrollview_observer#84]
### Platforms

dart

### Description

公司项目参考美图界面，目前是以下结构：

```
NestedScrollView
  headerSliverBuilder:SliverToBoxAdapter
  body:TabBarView
    [ListView, ListView]
```
左边listview是产品类别
右边listview是产品列表
## 要求实现效果：
左边产品类别可以控制产品列表跳到对应类别，
产品列表可以上下滚动，SliverToBoxAdapter正常缩放
## 请问使用scrollview_observer怎样实现？
![131716869263_ pic](https://github.com/fluttercandies/flutter_scrollview_observer/assets/4083885/fde14a82-a261-4e2a-946d-504cf9432b00)

**Comment by cjl84914** [comment]
I have done.

**Comment by Gxaasec** [comment]
@cjl84914 请问一下是如何解决，目前有类似需求，感谢
