### ISSUE TITLE
请问怎么根据滑动的距离计算出最近的一个index

### ISSUE THREAD

**Issue by CookerMa** [fluttercandies/flutter_scrollview_observer#85]

**Comment by CookerMa** [comment]
就是歌词的那种效果，但是每个item高度不一样，滑动一段距离之后，滚动到中间

https://github.com/fluttercandies/flutter_scrollview_observer/assets/10025209/4ee3f67c-9692-4d75-b907-d1bd1bcce26f

**Comment by LinXunFeng** [comment]
将 `ListViewObserver` 的 `leadingOffset` 的值设置为屏幕中间虚线的偏移量就可以了。

<img width="286" alt="image" src="https://github.com/fluttercandies/flutter_scrollview_observer/assets/19367531/24b74302-7184-4a5c-ab69-556974750add">
