### ISSUE TITLE
[Discussions] Selection Text 

### ISSUE THREAD

**Issue by dath7** [fluttercandies/flutter_scrollview_observer#86]
### Content

**Content**

Hi,  
I use [flutter_scrollview_observer](https://github.com/fluttercandies/flutter_scrollview_observer) for rendering list messages, and my case is after i select some texts and new message appear, the selection of text lost.

I have followed [wiki](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/2%E3%80%81Scrolling-to-the-specified-index-location).

I think the problem is my reversed list. Can you give me some recommend to solve this problem ? Thanks a lot.

My snippet code below:
```
ListViewObserver(
      controller: observerController,
      child:CustomSelectionArea(
            child: ListView.builder(
              physics: ChatObserverClampingScrollPhysics(observer: chatObserver),
              shrinkWrap: true,
              controller: widget.scrollController,
              reverse: true,
              itemCount: data.length,
              itemBuilder: (context, index) {
                  final message = data[index];
                  return ChatItem(message: message)
              }))
```

**Comment by LinXunFeng** [comment]
This should be a bug of `SelectionArea`.
Related issue: https://github.com/flutter/flutter/issues/124787

**Comment by dath7** [comment]
Sorry for my late reply. 
I think that related issue isn't same as my case. In my case, when new item appears, it's inserted at 0  so entire list has to rebuild and the selection of item lost.

Can you give me some recommend to solve this problem? Thanks a lot.

**Example**
![Screen Recording 2024-07-22 at 08 17 00](https://github.com/user-attachments/assets/fb609d5a-fd54-459a-b1cf-6fa6692cd821)

**Comment by LinXunFeng** [comment]
I think you can pause the update of `ListView` when selecting text.

```dart
bool canUpdateListView = true;

Widget resultWidget = ChatItemWidget(
  ...
);
resultWidget = SelectionArea(
  child: resultWidget,
  onSelectionChanged: (value) {
    canUpdateListView = value?.plainText == null;
    // The text is no longer selected. Update the ListView to display all the latest messages.
    if (canUpdateListView) {
      setState(() {});
    }
  },
);
return resultWidget;
```

```dart
_addMessage(int count) {
  chatObserver.standby(changeCount: count);
  needIncrementUnreadMsgCount = true;
  for (var i = 0; i < count; i++) {
    chatModels.insert(0, ChatDataHelper.createChatModel());
  }

  // Currently selecting text.
  if (!canUpdateListView) return;
  setState(() {});
}
```

**Comment by dath7** [comment]
Let me try.
Thanks a lot!
