### ISSUE TITLE
[Feature request] 在custom_scrollview下怎么跟Tabbar联动？

### ISSUE THREAD

**Issue by sjkyyt01** [fluttercandies/flutter_scrollview_observer#87]
### Platforms

Android

### Description

使用模块定位(Tabbar)在ListView下可以，在custom_scrollview下怎么做到？示例中好像不支持，ObserverUtils中只有针对ListView这种非custom_scrollview下的

**Comment by LinXunFeng** [comment]
`TabBar` 关联 `Sliver` 吗？`onObserveViewport` 可以知道当前哪个 `sliver` 是第一个。

**Comment by sjkyyt01** [comment]
深入了解了一下，custom_scrollview不能在左边定义一个纵向的Tabbar，改成了ListViewObserver，但现在又存在一个问题，就是NestedScrollView下ListViewObserver中的ListView部分上移后，SliverAppBar扩展的flexibleSpace不会收缩，把ListView中的scrollController移除后可以达到这个效果，但是跟Tabbar的联动效果就不存在了，现在我想达到在SliverAppBar未收缩前在ListView位置上滑时优先收缩SliverAppBar，然后再移动ListView自己的内容，反之，SliverAppBar收缩后，ListView如果到达顶部则扩展SliverAppBar，其实就就是达到美团外卖或者饿了么外卖店铺首页的效果

**Comment by LinXunFeng** [comment]
嗯嗯，不过这不是该库需要去做的
