### ISSUE TITLE
[Feature request] 如何无动画默认跳到指定位置 

### ISSUE THREAD

**Issue by peng093** [fluttercandies/flutter_scrollview_observer#89]
### Platforms

Android

### Description

比如  ，进入页面的时候，加载完所有列表默认跳转到第500条索引，scrollController.jumpTo(index: 500);会一直滑动很久才到，这种体验不好，需求是无动画的并且迅速定位到位置

**Comment by LinXunFeng** [comment]
与 https://github.com/fluttercandies/flutter_scrollview_observer/issues/5 重复

这个库只是观察，所以无法从根本上解决这个问题。
