### ISSUE TITLE
[Discussions] Application performance issue when using scrollview_observer library

### ISSUE THREAD

**Issue by ducky-z** [fluttercandies/flutter_scrollview_observer#98]
### Content

I find this library quite useful, and I'm using it to scroll to a specified index. However, I’m wondering, if I have a list with, say, 10,000 items and use a SliverList, will wrapping it in a ListViewObserver reduce the app’s performance for such a large list? Specifically, will it consume significant CPU or RAM resources, since it has to listen to continuous scrolling events?

**Comment by ducky-z** [comment]
> It will only iterate over and observe the items in the cache and display area, and if you do not implement callbacks such as `onObserve` and `onObserveAll`, it will not observe the items.
> 
> https://github.com/fluttercandies/flutter_scrollview_observer/blob/76c0310e237d22d64a127493c39cb871b51ea0ff/lib/src/common/observer_widget.dart#L311-L313
> 
> If you implement these callbacks, you can also adjust the observation frequency by setting `observeIntervalForScrolling`.
> 
> https://github.com/fluttercandies/flutter_scrollview_observer/blob/76c0310e237d22d64a127493c39cb871b51ea0ff/lib/src/common/observer_controller.dart#L31-L35

How can I customize "observeIntervalForScrolling"? I don't see in the documentation how to use it

**Comment by LinXunFeng** [comment]
> How can I customize "observeIntervalForScrolling"? I don't see in the documentation how to use it

Oh, I find time to add it to the wiki. you can set it as follows.

```dart
observerController. observeIntervalForScrolling = Duration(milliseconds: 500);
```

**Comment by ducky-z** [comment]
Thank you very much.
