### ISSUE TITLE
flutter_scrollview_observer可实现这样的效果吗，能否提供个在线例子?

### ISSUE THREAD

**Issue by lzc1022** [fluttercandies/flutter_scrollview_observer#99]
### Platforms

Android, iOS

### Description

怎么实现这样的效果，上下滑动切换对应的tab的索引值(京东商品详情效果)

### My code

![WechatIMG115](https://github.com/user-attachments/assets/8c67dd64-b1fb-4ce1-8965-cf50225d66a9)

**Comment by LinXunFeng** [comment]
看 [anchor_page](https://github.com/fluttercandies/flutter_scrollview_observer/blob/main/example/lib/features/scene/anchor_demo/anchor_page.dart) 这个示例
